### PR TITLE
Minor fixes, improvements + support for multiple tours, keyboard nav, rounded spotlight

### LINKED ISSUE #3: Bug fixes + new features (multiple tours, keyboard nav, rounded spotlight)
Hey @NiazMorshed2007! Really cool library - love that it's native shadcn and installs as owned source through the shad cli!

I'm Adam, one of the co-founders at @agnostack and @stackable-labs, and we're hoping to use shadcn-tour for guided onboarding in a new product we're working on. 

As we started integrating it, we ran into a few things that we'd need to fix for our use case (and presumably for some others like #1), and figured instead of just forking quietly we'd rather contribute back. Would love to submit a PR if you're open to it!

### Bugs we'd fix

- **`position: absolute` → `fixed`** on the overlay/highlight/tooltip - right now the tour breaks if the page scrolls or a parent has `position: relative`. Switching to `fixed` with viewport-relative coords from `getBoundingClientRect()` solves it.
- **Hardcoded 300×200 tooltip size** - mispositions when content is bigger or smaller. We'd swap in a `ResizeObserver` to auto-measure.
- **Stale closure in `nextStep`** -`onComplete` fires with wrong timing. Moving the completion check inside the state updater fixes it.
- **`startTour` checks prop instead of state** for completion, so it can't prevent restart after the tour finishes at runtime.

### Features we'd add

- **Multiple named tours**: register by ID, start with `startTour('tourName')`. This would potentially solve/help with #1 too!
- **Keyboard nav**: ArrowRight/Left to navigate, Escape to dismiss.
- **Skip button**: on every step.
- **Rounded spotlight**: swap `clipPath: polygon()` for an SVG mask so the cutout can have `border-radius`.
- **Scroll-into-view** for targets that are off-screen.
- **Lifecycle callbacks** : `onStart`, `onStepChange`, `onComplete`, `onSkip`.

Everything would be backward-compatible - existing usage wouldn't change at all.

Let me know if you'd be open to this, and if there's anything you'd want done differently!

I'll get a fork together in the interim to show what we're thinking...in case it would be helpful. 🙏

### PR DESCRIPTION
**Pull request by agrohs**
Resolves #3

## Summary

This PR makes shadcn-tour production-ready with bug fixes, visual improvements, and new features. All changes are backward-compatible — existing usage continues to work without modification.

## Bug Fixes

- **Fixed `position: absolute` → `position: fixed`** on all overlay layers. The previous approach broke in any scrollable layout or when a parent had `position: relative`. Position calculations updated to use viewport-relative coordinates.
- **Fixed hardcoded tooltip dimensions** (300×200) — tooltip now auto-sizes to content using `ResizeObserver`. Positioning calculations use measured dimensions.
- **Fixed stale closure in `nextStep`** — `onComplete` now fires at the correct time by moving the completion check inside the state updater.
- **Fixed `startTour` checking prop instead of state** for completion — prevents incorrect restart after runtime completion.
- **Added missing `lucide-react`** to registry dependencies.
- **Fixed tooltip stretching/jitter during step transitions** — rewrote `calculateContentPosition` to always resolve to absolute `top` + `left` values. The original returned a mix of `top`/`bottom`/`left`/`right` with centered positioning. Framer Motion interpolated both ends when animating between steps, causing the tooltip to stretch to fill the gap mid-animation. Now aligns tooltip based on which viewport half the target element is in (right-half → right-align, left-half → left-align).
- **Fixed tooltip misalignment from `right: 50` in initial prop** — removed `right: 50` and `top: 50` from the content tooltip's Framer Motion `initial` prop. When both `left` and `right` are set on a fixed element, the browser constrains the width, causing misalignment.
- **Fixed content-size jitter during AnimatePresence transitions** — added `contentTransitioning` ref that blocks `ResizeObserver` updates during step exit/enter. The observer was firing intermediate sizes as old content exited and new content entered, causing `contentPosition` to recalculate mid-animation. `onAnimationComplete` takes a final measurement after the transition settles.
- **Added `minWidth: 300`** to content tooltip for consistent sizing across steps with varying content lengths.

## Visual Improvements

- **Rounded spotlight cutout** — replaced `clipPath: polygon()` with SVG mask approach. New `padding` and `borderRadius` props on `TourStep` for configurable spotlight shape (both default to 8).
- **Highlight border respects border-radius** of target elements.
- **Memoized position calculations** — `calculateContentPosition` now runs once per render instead of 3 times.

## New Features

- **Multiple named tours** — register tours via `TourProvider tours={[...]}`, start by ID with `startTour('tourName')`. Addresses #1.
- **Keyboard navigation** — ArrowRight (next), ArrowLeft (previous), Escape (skip).
- **Skip button** — shown on every step except the last (where "Finish" is shown). Per-step opt-out via `showSkip: false`.
- **Close button** — optional X icon in top-right corner, enabled via `closeable` prop on `TourProvider` or per-step override. Styled to match native shadcn primitives.
- **Lifecycle callbacks** — `onStart`, `onStepChange`, `onComplete`, `onSkip` (all receive `tourId`).
- **Scroll-into-view** — off-screen target elements are smoothly scrolled into view before highlighting.

## Demo

- Original `/dashboard` demo is untouched (proves backward compatibility)
- New `/multi-tour` demo shows the new `tours` prop, tour selection dialog, lifecycle callbacks (logged to console), rounded spotlights, and keyboard navigation

## Migration

Existing usage is fully backward-compatible. New features are opt-in:

```tsx
// Before (still works):
<TourProvider onComplete={handleComplete}>

// New capabilities:
<TourProvider
  tours={[
    { id: 'intro', steps: introSteps },
    { id: 'advanced', steps: advancedSteps },
  ]}
  closeable
  onComplete={(tourId) => console.log(`${tourId} completed`)}
  onSkip={(tourId, step) => console.log(`${tourId} skipped at step ${step}`)}
>
```

### CODE REVIEW

File: components/tour.tsx [hunk 1]
```diff
@@ -210,55 +309,63 @@ export function TourProvider({
...
         setIsTourCompleted,
+        activeTourId,
       }}
     >
       {children}
       <AnimatePresence>
         {currentStep >= 0 && elementPosition && (
           <>
-            <motion.div
+            <motion.svg
```
Comment (agrohs) [inline components/tour.tsx:340]: Wasn't sure on here why this was using style/clipPath, cleaned up - but if this does not work - just let me know!

File: public/tour.json [hunk 2]
```diff
@@ -1,9 +1,10 @@
 {
   "name": "tour",
   "type": "registry:block",
-  "description": "",
+  "description": "A guided tour component for shadcn/ui with multiple tours, keyboard navigation, rounded spotlight, and lifecycle callbacks.",
```
Comment (agrohs) [inline public/tour.json:4]: Added description here, but feel free to adjust/clean up as you see fit @NiazMorshed2007
